version: "3.4"
services:
  node:
    build:
      context: .
      target: production
    image: registry.cn-hangzhou.aliyuncs.com/smartvis/smartvis-backend:alpine
    restart: always
    volumes:
      - ./config:/usr/src/app/config:ro
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - redis
      - mongo
      - influxdb
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx:/etc/nginx:ro
    ports:
      - 80:80
      - 443:443
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ~/databases/smartvis/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: smartvis
      MYSQL_USER: smartvis
      MYSQL_PASSWORD: smartvis
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - ~/databases/smartvis/mongo/db:/data/db
      - ~/databases/smartvis/mongo/configdb:/data/configdb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
  influxdb:
    image: influxdb:alpine
    restart: always
    volumes:
    - ~/databases/smartvis/influxdb:/var/lib/influxdb
    ports:
    - 8086:8086
