version: "3"
services:
  db:
    image: mysql:5.7
    container_name: smartvis_mysql
    volumes:
      - ~/databases/smartvis/mysql:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: smartvis
      MYSQL_USER: smartvis
      MYSQL_PASSWORD: smartvis
  node:
    build: .
    image: idvbxlab/smartvis-backend:alpine
    container_name: smartvis_node
    restart: always
    volumes:
      - ./config:/usr/src/app/config:ro
    ports:
      - 8080:8080
    depends_on:
      - db
