version: "3.4"
services:
  node:
    build:
      context: .
      target: production
    image: registry.cn-hangzhou.aliyuncs.com/smartvis/smartvis-backend:alpine
    restart: always
    volumes:
      - ./config:/usr/src/app/config:ro
    ports:
      - 8080:8080
    depends_on:
      - influxdb
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx:/etc/nginx:ro
    ports:
      - 80:80
      - 443:443
  influxdb:
    image: influxdb:alpine
    restart: always
    volumes:
      - ~/databases/smartvis/influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
